# Site settings
author: Wielfried Zouantcha
title: Kode Kafe 
header-img: img/home-bg.png
email: zouantchaw74@gmail.com
copyright_name: Wielfried Zouantcha
description: > # this means to ignore newlines until "baseurl:"
  Coding 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  zouantchaw

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
